import type { Metadata } from "next";
import { Inter,Sedan, Playfair_Display, Dancing_Script, Pacifico, Caveat } from "next/font/google";
import "./globals.css";
import Navigation from "../components/Navigation";

const roboto_init = Sedan({
  subsets:['latin'],
  weight:['400'],
  variable:'--font-sedan',
})

const playfair_display = Playfair_Display({
  subsets:['latin'],
  weight: '600',
  variable:'--font-playfair_display',
})

const dancing = Dancing_Script({
  subsets:['latin'],
  weight: '400',
  variable:'--dancing',
})
const pacifico = Pacifico({
  subsets:['latin'],
  weight: '400',
  variable:'--pacifico',
})
const caveat = Caveat({
  subsets:['latin'],
  weight: '400',
  variable:'--caveat',
})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mis 15 años",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto_init.variable} ${playfair_display.variable} ${dancing.variable} ${pacifico.variable} ${caveat.variable}`}>
        <Navigation/>
        {children}
        </body>
    </html>
  );
}
