import type { Metadata } from "next";
import { Inter,Roboto, Playfair_Display } from "next/font/google";
import "./globals.css";
import Navigation from "../components/Navigation";

const roboto_init = Roboto({
  subsets:['latin'],
  weight:['100'],
  variable:'--font-roboto',
})

const playfair_display = Playfair_Display({
  subsets:['latin'],
  weight: '600',
  variable:'--font-playfair_display',
})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mis 15 años",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto_init.variable} ${playfair_display.variable}`}>
        <Navigation/>
        {children}
        </body>
    </html>
  );
}
